#!/bin/bash

# Date formatting
NOW=$(date -u)
FORMATTED=$(grep "[0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}" -o -E <<< $NOW)
MINUTES=$(echo $FORMATTED | grep ":([0-9]{1,2}):" -o -E | grep "[0-9]{1,2}" -o -E)
OLD_MINUTES=$(cat README.md | grep ":([0-9]{1,2}):" -o -E | grep "[0-9]{1,2}" -o -E)
MAGIC=50

# Eventual wait
if (( MINUTES == OLD_MINUTES )); then
    sleep $MAGIC
fi

# Cleanup
rm -rf tmp
mkdir tmp
cd tmp

# Git stuff
git config --global user.email $GITHUB_EMAIL
git init
git remote add origin https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/mpsq/what-time-is-it.git
git pull origin master --depth 1
echo "# ${FORMATTED} (UTC)" > README.md
git add README.md
git commit -m "update README.md"
git push -u origin master
